# Automatically generated by discover_functions.py
# DO NOT EDIT MANUALLY

DISCOVERED_FUNCTIONS = aaaaaa cdiv csroot d1mach fdump i1mach lsame pimach pythag qwgtc r1mach

DEPENDENCY_FUNCTIONS = xermsg ivout j4save xercnt xerhlt xerprn xersve xgetua

ALL_TESTED_FUNCTIONS = $(DISCOVERED_FUNCTIONS) $(DEPENDENCY_FUNCTIONS)